### ISSUE TITLE
Error when creating item.

### ISSUE THREAD

**Issue by brimwats** [HBLL-Collection-Development/omeka-s-any-cloud#10]
**Describe the bug**
Cannot create items.

**To Reproduce**
1. set anycloud to dropbox
2. get dropbox developer
3. add token to anycloud
4. try to add an item
5. Omeka S encountered an error

**Comment by jaredhowland** [comment]
v1.1.2 should fix this issue. Please let me know if you continue experiencing problems.

**Comment by brimwats** [comment]
Installation now fails with "The Any Cloud components via composer should be installed. See module’s installation documentation."

**Comment by brimwats** [comment]
May be related to the StyleCI failing: https://github.styleci.io/repos/167904424

**Comment by jaredhowland** [comment]
Are you downloading from the `master` directory or from the `Releases` section? Download file should be at [https://github.com/HBLL-Collection-Development/omeka-s-any-cloud/releases/download/v1.1.2/AnyCloudv1.1.2.zip]

**Comment by brimwats** [comment]
Whoooooops 😳 I don't know how I managed that one! I will retry with the release and follow up if any issues!
