### ISSUE TITLE
S3 access denied

### ISSUE THREAD

**Issue by hxsllc** [HBLL-Collection-Development/omeka-s-any-cloud#14]
I think this is more about instructions, or possibly that S3 has changed? I have an S3 bucket and when I add media to an item (in my case, via URL) it properly retrieves and uploads the item. However, the newly generated images (derivatives) are not viewable. I receive "access denied" XML responses from S3 URL - until I go into S3, locate the file, and choose "Make public" individually for each item.

I've tried a bucket that was already public, but it seemed to me that when AnyCloud uploaded the file - it didn't follow the bucket policy. (I'm not an expert on AWS cloud infrastructure or security policies).

Here's an example of the S3 response, I think it's pretty standard.

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>9729D463FE8C1263</RequestId>
<HostId>
wtrPOPXuXwnpmJlL74/WMKS1LdfPSUt38BhwDYm0xQys0FKIxa2zihffDkbyFgmltdEhnXZycYI=
</HostId>
</Error>`

I'm looking here https://aws.amazon.com/premiumsupport/knowledge-center/s3-troubleshoot-403/ but not seeing any pointers about why an uploaded file would show access denied if it is being accessed via an access key.
I tried creating a brand new bucket and left it with block public access (since we are using a key to access things anyway - via the module config settings). This had the same effect.

So I just wanted to reach out and see if you had any thoughts or knowledge. Perhaps it's something I am missing, but it seems the access key has "full access" and since I tried in both a public bucket and a private bucket, and got the same result - there could be an issue.

**Comment by jaredhowland** [comment]
I am not having problems accessing my S3 bucket using the latest version of the plugin and latest version of Omeka-S. This makes me think that it might be a configuration error on your S3 bucket. Can you double-check things again and let me know of any other error messages you see? I'll keep looking but am having a hard time tracking this one down.

**Comment by hxsllc** [comment]
Ok sure sounds like it's on my end! Will try again

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jaredhowland** [comment]
I started over and created a new bucket and got the same message as you. Omeka creates directories in the new bucket (original, large, etc). When I selected all the Omega-related directories from my S3 console and made them all public, the message went away. This is the closest I can come to replicating the issue so I will be closing it.

**Comment by hxsllc** [comment]
OK I see the confusion. I was assuming since the module requested AWS special key that the bucket did not need to be public. And of course by default Amazon encourages buckets to not be made public. So the special access key that the module requires is just used for upload operation. Omeka-S itself expects (needs) the bucket to be public in order to view the images (it doesn't use access key to view/display, I think that's correct). Maybe this is not a point worth communicating in the instructions since it is so obvious - but I often find people get stuck on obvious things. Whatever you think is best!

**Comment by jaredhowland** [comment]
A recent contribution by @jajm, and added to v1.1.5, makes this more intuitive and sets the visibility of S3-like calls to public by default. Hopefully this prevents others from having the same problem.
