### ISSUE TITLE
New Dropbox OAuth requires scoped access

### ISSUE THREAD

**Issue by pgorla** [HBLL-Collection-Development/omeka-s-any-cloud#17]
**Describe the bug**
Dropbox changed their permissions settings to now require all permissions to have scoped access (whether to the full Dropbox account or just one folder). The new API is here: https://www.dropbox.com/developers/documentation

When I try to upload and then read from an item, this is the error I see:

```
GuzzleHttp\Exception\ClientException: Client error: `POST https://api.dropboxapi.com/2/files/get_temporary_link` resulted in a `401 Unauthorized` response:
{"error_summary": "missing_scope/", "error": {".tag": "missing_scope", "required_scope": "files.content.read"}}
```

**To Reproduce**
1. Set Dropbox as the backend
2. Upload an item
3. Navigate to 'Items'

**Expected behavior**
Initially the screen just displayed "Omeka S encountered an error", and I enabled development mode to see the error.

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04
- Version 2.1.2

Thank you for your work! My plan for a workaround is to use the legacy v2 permissions. Technically it's deprecated but Dropbox is still offering it as a solution

**Comment by jaredhowland** [comment]
I think the latest versions have fixed this problem. I'll keep this open for a bit but will close if I don't hear otherwise.
