### ISSUE TITLE
AWS PHP SDK Notice

### ISSUE THREAD

**Issue by jbuwlaw** [HBLL-Collection-Development/omeka-s-any-cloud#20]
**Describe the bug**
I am getting "Trying to access array offset on value of type null in _OmekaInstallationPath_/modules/AnyCloud/vendor/aws/aws-sdk-php/src/RetryMiddleware.php on line 146" in my apache logs.  In development mode for omeka s, I get the same notice on each page.  I have been looking around and it seems that other projects using this php aws sdk are getting the same notification with PHP version 7.4, which I am at.  This is on Omeka S 2.1.2 and Anycloud 1.1.5.  

**To Reproduce**
1. Install the module
2. Check the apache log

**Expected behavior**
To not see this notice.

**Desktop (please complete the following information):**
- Browser - Any
- Version - Omeka S 2.1.2, Anycloud 1.1.5

**Comment by jaredhowland** [comment]
Does the latest release fix this issue?
