### ISSUE TITLE
Dropbox error

### ISSUE THREAD

**Issue by Dominique56** [HBLL-Collection-Development/omeka-s-any-cloud#22]
Any Cloud version 2.0.0
Omeka S 3.0.1
here is the message 

Spatie\Dropbox\Exceptions\BadRequest: path/not_found/ in /modules/AnyCloud/vendor/spatie/dropbox-api/src/Client.php:649
Stack trace:
#0 /modules/AnyCloud/vendor/spatie/dropbox-api/src/Client.php(638): Spatie\Dropbox\Client->determineException(Object(GuzzleHttp\Exception\ClientException))
#1 /modules/AnyCloud/vendor/spatie/dropbox-api/src/Client.php(257): Spatie\Dropbox\Client->rpcEndpointRequest('files/get_tempo...', Array)
#2 //modules/AnyCloud/vendor/spatie/flysystem-dropbox/src/DropboxAdapter.php(245): Spatie\Dropbox\Client->getTemporaryLink('square/7236f095...')
#3 /modules/AnyCloud/src/File/Store/AnyCloud.php(69): Spatie\FlysystemDropbox\DropboxAdapter->getTemporaryLink('square/7236f095...')
#4 /application/src/Api/Representation/AbstractResourceRepresentation.php(269): AnyCloud\File\Store\AnyCloud->getUri('square/7236f095...')
#5 /application/src/Api/Representation/MediaRepresentation.php(85): Omeka\Api\Representation\AbstractResourceRepresentation->getFileUrl('square', '7236f0959729aa7...', '.jpg')
#6 /application/src/Api/Representation/AbstractRepresentation.php(122): Omeka\Api\Representation\MediaRepresentation->thumbnailUrl('square')
#7 application/src/View/Helper/Thumbnail.php(21): Omeka\Api\Representation\AbstractRepresentation->thumbnailDisplayUrl('square')
#8 /application/src/Api/Representation/AbstractResourceEntityRepresentation.php(573): Omeka\View\Helper\Thumbnail->__invoke(Object(Omeka\Api\Representation\ItemRepresentation), 'square')
#9 /application/view/omeka/admin/item/browse.phtml(99): Omeka\Api\Representation\AbstractResourceEntityRepresentation->linkPretty()
#10 vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/home/alla6772/...')
#11 /vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#12 /vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#13 /vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#14 /vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#15 /vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#16 /vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#17 /vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#18 /vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#19 /index.php(21): Laminas\Mvc\Application->run()
#20 {main}

Thank you for your help

**Comment by jonfackrell** [comment]
@Dominique56 It looks the requested file isn't stored in Dropbox. If you just installed this module and didn't move the files to Dropbox, this would be expected. If that's not the case, it would be helpful to have some more context of what happened to cause this error.

**Comment by Dominique56** [comment]
I don't understand because for me the idea is to recover a file stored on Dropbox and not to move the files stored on the site to Dropbox

**Comment by jonfackrell** [comment]
In Omeka you can only have one file store. If you install this module and set Dropbox as the storage option, Omeka will just assume that everything is in Dropbox. So if you had previously uploaded files to Omeka, prior to installing this module, you will need to manually move them to Dropbox (or whichever cloud storage provider you choose.)

**Comment by Dominique56** [comment]
I just uploaded them to Dropbox, but it doesn't work.
Do we have to remove them one by one from Omeka and then install them again?

**Comment by jonfackrell** [comment]
You shouldn't, but you do have to make sure you maintain the same folder structure.

**Comment by Dominique56** [comment]
I deleted everything but when I want to load a file I have this message GuzzleHttp \ Exception \ ClientException
Client error: `POST https: // api.dropboxapi.com / 2 / files / get_metadata` resulted in a` 401 Unauthorized` response: {"error_summary": "expired_access_token / ..", "error": {".tag ":" expired_access_token "}}

**Comment by Dominique56** [comment]
I created another API and here is the new message
error
 Spatie \ Dropbox \ Exceptions \ BadRequest
path / not_found /.

Details:

Spatie \ Dropbox \ Exceptions \ BadRequest: path / not_found /. in /modules/AnyCloud/vendor/spatie/dropbox-api/src/Client.php:649
Stack trace:
# 0 /modules/AnyCloud/vendor/spatie/dropbox-api/src/Client.php(638): Spatie \ Dropbox \ Client-> determineException (Object (GuzzleHttp \ Exception \ ClientException))
# 1 /modules/AnyCloud/vendor/spatie/dropbox-api/src/Client.php(257): Spatie \ Dropbox \ Client-> rpcEndpointRequest ('files / get_tempo ...', Array)
# 2 /modules/AnyCloud/vendor/spatie/flysystem-dropbox/src/DropboxAdapter.php(245): Spatie \ Dropbox \ Client-> getTemporaryLink ('square / f43b0e39 ...')
# 3 /modules/AnyCloud/src/File/Store/AnyCloud.php(69): Spatie \ FlysystemDropbox \ DropboxAdapter-> getTemporaryLink ('square / f43b0e39 ...')
# 4 /application/src/Api/Representation/AbstractResourceRepresentation.php(269): AnyCloud \ File \ Store \ AnyCloud-> getUri ('square / f43b0e39 ...')
# 5 /application/src/Api/Representation/MediaRepresentation.php(85): Omeka \ Api \ Representation \ AbstractResourceRepresentation-> getFileUrl ('square', 'f43b0e39043c433 ...', '. jpg ')
# 6 /application/src/Api/Representation/AbstractRepresentation.php(122): Omeka \ Api \ Representation \ MediaRepresentation-> thumbnailUrl ('square')
# 7 /application/src/View/Helper/Thumbnail.php(21): Omeka \ Api \ Representation \ AbstractRepresentation-> thumbnailDisplayUrl ('square')
# 8 /application/src/Api/Representation/AbstractResourceEntityRepresentation.php(573): Omeka \ View \ Helper \ Thumbnail -> __ invoke (Object (Omeka \ Api \ Representation \ ItemRepresentation), 'square ')
# 9 application/view/omeka/admin/item/browse.phtml(99): Omeka \ Api \ Representation \ AbstractResourceEntityRepresentation-> linkPretty ()
# 10 /vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include ('/ home / alla6772 / ...')
# 11 /vendor/laminas/laminas-view/src/View.php(206): Laminas \ View \ Renderer \ PhpRenderer-> render (NULL)
# 12 /vendor/laminas/laminas-view/src/View.php(235): Laminas \ View \ View-> render (Object (Laminas \ View \ Model \ ViewModel))
# 13 /vendor/laminas/laminas-view/src/View.php(199): Laminas \ View \ View-> renderChildren (Object (Laminas \ View \ Model \ ViewModel))
# 14 /vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas \ View \ View-> render (Object (Laminas \ View \ Model \ ViewModel ))
# 15 /vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas \ Mvc \ View \ Http \ DefaultRenderingStrategy-> render (Object (Laminas \ Mvc \ MvcEvent))
# 16 /vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas \ EventManager \ EventManager-> triggerListeners (Object (Laminas \ Mvc \ MvcEvent))
# 17 /vendor/laminas/laminas-mvc/src/Application.php(366): Laminas \ EventManager \ EventManager-> triggerEvent (Object (Laminas \ Mvc \ MvcEvent))
# 18 /vendor/laminas/laminas-mvc/src/Application.php(347): Laminas \ Mvc \ Application-> completeRequest (Object (Laminas \ Mvc \ MvcEvent))
# 19 /index.php(21): Laminas \ Mvc \ Application-> run ()
# 20 {main}

**Comment by Dominique56** [comment]
I found, you had to be connected to Dropbox with the local application and not on the site
thank you so much

**Comment by Dominique56** [comment]
Sorry but the morning the same error

 Spatie\Dropbox\Exceptions\BadRequest
path/not_found/...

Détails :

Spatie\Dropbox\Exceptions\BadRequest: path/not_found/... in modules/AnyCloud/vendor/spatie/dropbox-api/src/Client.php:649
Stack trace:
#0 /modules/AnyCloud/vendor/spatie/dropbox-api/src/Client.php(638): Spatie\Dropbox\Client->determineException(Object(GuzzleHttp\Exception\ClientException))
#1 /modules/AnyCloud/vendor/spatie/dropbox-api/src/Client.php(257): Spatie\Dropbox\Client->rpcEndpointRequest('files/get_tempo...', Array)
#2 /modules/AnyCloud/vendor/spatie/flysystem-dropbox/src/DropboxAdapter.php(245): Spatie\Dropbox\Client->getTemporaryLink('square/c837715c...')
#3 /modules/AnyCloud/src/File/Store/AnyCloud.php(69): Spatie\FlysystemDropbox\DropboxAdapter->getTemporaryLink('square/c837715c...')
#4 /application/src/Api/Representation/AbstractResourceRepresentation.php(269): AnyCloud\File\Store\AnyCloud->getUri('square/c837715c...')
#5 /application/src/Api/Representation/MediaRepresentation.php(85): Omeka\Api\Representation\AbstractResourceRepresentation->getFileUrl('square', 'c837715ca9734d6...', '.jpg')
#6 /application/src/Api/Representation/AbstractRepresentation.php(122): Omeka\Api\Representation\MediaRepresentation->thumbnailUrl('square')
#7 /application/src/View/Helper/Thumbnail.php(21): Omeka\Api\Representation\AbstractRepresentation->thumbnailDisplayUrl('square')
#8 application/src/Api/Representation/AbstractResourceEntityRepresentation.php(573): Omeka\View\Helper\Thumbnail->__invoke(Object(Omeka\Api\Representation\ItemRepresentation), 'square')
#9 /home/alla6772/public_html/ged/application/view/omeka/admin/item/browse.phtml(99): Omeka\Api\Representation\AbstractResourceEntityRepresentation->linkPretty()
#10 /vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/home/alla6772/...')
#11 /vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#12 /vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#13 /vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#14 /vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#15 /vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#16 /vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#17 /vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#18 /vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#19 /index.php(21): Laminas\Mvc\Application->run()
#20 {main}

I don't unterstand......

**Comment by Dominique56** [comment]
Error this morning
GuzzleHttp\Exception\ClientException
Client error: `POST https://api.dropboxapi.com/2/files/get_metadata` resulted in a `401 Unauthorized` response: {"error_summary": "missing_scope/...", "error": {".tag": "missing_scope", "required_scope": "files.metadata.read"}} 

thanks for help

**Comment by jaredhowland** [comment]
I think the latest versions have fixed this problem. I'll keep this open for a bit but will close if I don't hear otherwise.

**Comment by jaredhowland** [comment]
I think the latest versions have fixed this problem. I'll keep this open for a bit but will close if I don't hear otherwise.
