### ISSUE TITLE
Error Dropbox

### ISSUE THREAD

**Issue by Dominique56** [HBLL-Collection-Development/omeka-s-any-cloud#25]
Unable to upload a file this morning while already uploaded files are visible
Here is the error message:
Warning: fclose (): supplied resource is not a valid stream resource in ... / modules / AnyCloud / src / File / Store / AnyCloud.php on line 44
Thank you for your advice

**Comment by jaredhowland** [comment]
I think the latest versions have fixed this problem. I'll keep this open for a bit but will close if I don't hear otherwise.

**Comment by y-a-v-a** [comment]
TypeError: fclose(): supplied resource is not a valid stream resource in /shared/usr/xyz/DOMAIN/HTML/archive/modules/AnyCloud/src/File/Store/Flysystem.php:27


Same error with Google Cloud Storage on v3.1.5

**Comment by y-a-v-a** [comment]
Fixed it by adding a check
```php
if (is_resource($fh)) {
    fclose($fh);
}
```

**Comment by jajm** [comment]
Added the check in cb23551
Thanks
