### ISSUE TITLE
0.3.2 Release is missing Module.php

### ISSUE THREAD

**Issue by jonfackrell** [HBLL-Collection-Development/omeka-s-any-cloud#3]
I just downloaded the zip package for the 0.3.2 release and it's missing the Module.php file so you get an error on the admin side which prevents you from activating the module.

**Comment by jaredhowland** [comment]
I updated to v1.0.0 that fixes this issue. Can you install the module again and see if it fixes #4 as well?

**Comment by jonfackrell** [comment]
I'm still getting the same error. Here is the full error message with the
stack trace:

2019-03-12T21:18:08+00:00 ERR (3):
Zend\Form\Exception\InvalidElementException: A plugin by the name
"AnyCloud\Form\Configform" was not found in the plugin manager
Zend\Form\FormElementManager\FormElementManagerV3Polyfill in /home/forge/
spc.ask-a-librarian.com/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerTrait.php:41
Stack trace:
#0 /home/forge/spc.ask-a-librarian.com/modules/AnyCloud/Module.php(72):
Zend\Form\FormElementManager\FormElementManagerV3Polyfill->get('AnyCloud\\Form\\C...')
#1 /home/forge/
spc.ask-a-librarian.com/application/src/Controller/Admin/ModuleController.php(280):
AnyCloud\Module->getConfigForm(Object(Zend\View\Renderer\PhpRenderer))
#2 /home/forge/
spc.ask-a-librarian.com/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78):
Omeka\Controller\Admin\ModuleController->configureAction()
#3 /home/forge/
spc.ask-a-librarian.com/vendor/zendframework/zend-eventmanager/src/EventManager.php(322):
Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /home/forge/
spc.ask-a-librarian.com/vendor/zendframework/zend-eventmanager/src/EventManager.php(179):
Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent),
Object(Closure))
#5 /home/forge/
spc.ask-a-librarian.com/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106):
Zend\EventManager\EventManager->triggerEventUntil(Object(Closure),
Object(Zend\Mvc\MvcEvent))
#6 /home/forge/
spc.ask-a-librarian.com/vendor/zendframework/zend-mvc/src/DispatchListener.php(138):
Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request),
Object(Zend\Http\PhpEnvironment\Response))
#7 /home/forge/
spc.ask-a-librarian.com/vendor/zendframework/zend-eventmanager/src/EventManager.php(322):
Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /home/forge/
spc.ask-a-librarian.com/vendor/zendframework/zend-eventmanager/src/EventManager.php(179):
Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent),
Object(Closure))
#9 /home/forge/
spc.ask-a-librarian.com/vendor/zendframework/zend-mvc/src/Application.php(332):
Zend\EventManager\EventManager->triggerEventUntil(Object(Closure),
Object(Zend\Mvc\MvcEvent))
#10 /home/forge/spc.ask-a-librarian.com/index.php(21):
Zend\Mvc\Application->run()
#11 {main}
