### ISSUE TITLE
Not 4.0.0 compatible

### ISSUE THREAD

**Issue by ccordero5500** [HBLL-Collection-Development/omeka-s-any-cloud#34]
Not much to describe here. When I unzip AnyCloudv2.0.0.zip to the modules directory in Omeka S 4.0.0, start the server for the first time and do initial setup, when I go to Modules it says `Error: Any Cloud requires Omeka S ^3.0.0`.

**Comment by LATAEVIA** [comment]
I'm getting the same error. I wonder how/where AnyCloudv2.0.0 is checking for the Omeka S version, or if its possible the Omeka S 4.0.0 code is now declaring it version in a new place?
