### ISSUE TITLE
GuzzleHttp\Promise\RejectionException ERROR when adding some items

### ISSUE THREAD

**Issue by CSSSchaffer** [HBLL-Collection-Development/omeka-s-any-cloud#36]
Hi, we haven't changed our Any Cloud module, still running on 2.0.0 and Omeka S version 3.2.0, and we're getting this error that wasn't happening before when trying to add an item with media. I checked our Amazon Service credentials in the settings, which were correct. I also thought maybe it had to do with too large a file size at first, but that wasn't it. Any ideas as to why this is happening?  Note, this error happens when we run Omeka S on PHP 8, but the issue resolves if we roll back to PHP 7.4. 

GuzzleHttp\Promise\RejectionException

The promise was rejected with reason: Invoking the wait callback did not resolve the promise

Details:

GuzzleHttp\Promise\RejectionException: The promise was rejected with reason: Invoking the wait callback did not resolve the promise in /home/schaffer/[digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/functions.php:112](http://digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/functions.php:112)
Stack trace:
#0 /home/schaffer/[digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Promise.php(75)](http://digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Promise.php(75)): GuzzleHttp\Promise\exception_for('Invoking the wa...')
#1 /home/schaffer/[digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Coroutine.php(65)](http://digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Coroutine.php(65)): GuzzleHttp\Promise\Promise->wait()
#2 /home/schaffer/[digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Promise.php(246)](http://digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Promise.php(246)): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}(true)
#3 /home/schaffer/[digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Promise.php(223)](http://digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Promise.php(223)): GuzzleHttp\Promise\Promise->invokeWaitFn()
#4 /home/schaffer/[digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Promise.php(267)](http://digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Promise.php(267)): GuzzleHttp\Promise\Promise->waitIfPending()
#5 /home/schaffer/[digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Promise.php(225)](http://digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Promise.php(225)): GuzzleHttp\Promise\Promise->invokeWaitList()
#6 /home/schaffer/[digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Promise.php(62)](http://digitalcollections.union.edu/modules/AnyCloud/vendor/guzzlehttp/promises/src/Promise.php(62)): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /home/schaffer/[digitalcollections.union.edu/modules/AnyCloud/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(34)](http://digitalcollections.union.edu/modules/AnyCloud/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(34)): GuzzleHttp\Promise\Promise->wait()
#8 /home/schaffer/[digitalcollections.union.edu/modules/AnyCloud/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(611)](http://digitalcollections.union.edu/modules/AnyCloud/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(611)): Aws\S3\S3Client->upload('omekatest-union...', 'original/0412df...', Resource id #1221, 'public-read', Array)
#9 /home/schaffer/[digitalcollections.union.edu/modules/AnyCloud/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(134)](http://digitalcollections.union.edu/modules/AnyCloud/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(134)): League\Flysystem\AwsS3v3\AwsS3Adapter->upload('original/0412df...', Resource id #1221, Object(League\Flysystem\Config))
#10 /home/schaffer/[digitalcollections.union.edu/modules/AnyCloud/vendor/league/flysystem/src/Filesystem.php(102)](http://digitalcollections.union.edu/modules/AnyCloud/vendor/league/flysystem/src/Filesystem.php(102)): League\Flysystem\AwsS3v3\AwsS3Adapter->write('original/0412df...', Resource id #1221, Object(League\Flysystem\Config))
#11 /home/schaffer/[digitalcollections.union.edu/modules/AnyCloud/src/File/Store/AnyCloud.php(43)](http://digitalcollections.union.edu/modules/AnyCloud/src/File/Store/AnyCloud.php(43)): League\Flysystem\Filesystem->put('original/0412df...', Resource id #1221, Object(League\Flysystem\Config))
#12 /home/schaffer/[digitalcollections.union.edu/application/src/File/TempFile.php(227)](http://digitalcollections.union.edu/application/src/File/TempFile.php(227)): AnyCloud\File\Store\AnyCloud->put('/tmp/omekaZ0DJn...', 'original/0412df...')
#13 /home/schaffer/[digitalcollections.union.edu/application/src/File/TempFile.php(238)](http://digitalcollections.union.edu/application/src/File/TempFile.php(238)): Omeka\File\TempFile->store('original')
#14 /home/schaffer/[digitalcollections.union.edu/application/src/File/TempFile.php(435)](http://digitalcollections.union.edu/application/src/File/TempFile.php(435)): Omeka\File\TempFile->storeOriginal()
#15 /home/schaffer/[digitalcollections.union.edu/application/src/Media/Ingester/Upload.php(62)](http://digitalcollections.union.edu/application/src/Media/Ingester/Upload.php(62)): Omeka\File\TempFile->mediaIngestFile(Object(Omeka\Entity\Media), Object(Omeka\Api\Request), Object(Omeka\Stdlib\ErrorStore))
#16 /home/schaffer/[digitalcollections.union.edu/application/src/Api/Adapter/MediaAdapter.php(169)](http://digitalcollections.union.edu/application/src/Api/Adapter/MediaAdapter.php(169)): Omeka\Media\Ingester\Upload->ingest(Object(Omeka\Entity\Media), Object(Omeka\Api\Request), Object(Omeka\Stdlib\ErrorStore))
#17 /home/schaffer/[digitalcollections.union.edu/application/src/Api/Adapter/AbstractEntityAdapter.php(630)](http://digitalcollections.union.edu/application/src/Api/Adapter/AbstractEntityAdapter.php(630)): Omeka\Api\Adapter\MediaAdapter->hydrate(Object(Omeka\Api\Request), Object(Omeka\Entity\Media), Object(Omeka\Stdlib\ErrorStore))
#18 /home/schaffer/[digitalcollections.union.edu/application/src/Api/Adapter/ItemAdapter.php(257)](http://digitalcollections.union.edu/application/src/Api/Adapter/ItemAdapter.php(257)): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Media), Object(Omeka\Stdlib\ErrorStore))
#19 /home/schaffer/[digitalcollections.union.edu/application/src/Api/Adapter/AbstractEntityAdapter.php(630)](http://digitalcollections.union.edu/application/src/Api/Adapter/AbstractEntityAdapter.php(630)): Omeka\Api\Adapter\ItemAdapter->hydrate(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#20 /home/schaffer/[digitalcollections.union.edu/application/src/Api/Adapter/AbstractEntityAdapter.php(341)](http://digitalcollections.union.edu/application/src/Api/Adapter/AbstractEntityAdapter.php(341)): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#21 /home/schaffer/[digitalcollections.union.edu/application/src/Api/Manager.php(224)](http://digitalcollections.union.edu/application/src/Api/Manager.php(224)): Omeka\Api\Adapter\AbstractEntityAdapter->create(Object(Omeka\Api\Request))
#22 /home/schaffer/[digitalcollections.union.edu/application/src/Api/Manager.php(78)](http://digitalcollections.union.edu/application/src/Api/Manager.php(78)): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#23 /home/schaffer/[digitalcollections.union.edu/application/src/Mvc/Controller/Plugin/Api.php(99)](http://digitalcollections.union.edu/application/src/Mvc/Controller/Plugin/Api.php(99)): Omeka\Api\Manager->create('items', Array, Array, Array)
#24 /home/schaffer/[digitalcollections.union.edu/modules/Collecting/src/Controller/Site/IndexController.php(71)](http://digitalcollections.union.edu/modules/Collecting/src/Controller/Site/IndexController.php(71)): Omeka\Mvc\Controller\Plugin\Api->create('items', Array, Array)
#25 /home/schaffer/[digitalcollections.union.edu/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77)](http://digitalcollections.union.edu/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77)): Collecting\Controller\Site\IndexController->submitAction()
#26 /home/schaffer/[digitalcollections.union.edu/vendor/laminas/laminas-eventmanager/src/EventManager.php(321)](http://digitalcollections.union.edu/vendor/laminas/laminas-eventmanager/src/EventManager.php(321)): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#27 /home/schaffer/[digitalcollections.union.edu/vendor/laminas/laminas-eventmanager/src/EventManager.php(178)](http://digitalcollections.union.edu/vendor/laminas/laminas-eventmanager/src/EventManager.php(178)): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#28 /home/schaffer/[digitalcollections.union.edu/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103)](http://digitalcollections.union.edu/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103)): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#29 /home/schaffer/[digitalcollections.union.edu/vendor/laminas/laminas-mvc/src/DispatchListener.php(139)](http://digitalcollections.union.edu/vendor/laminas/laminas-mvc/src/DispatchListener.php(139)): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#30 /home/schaffer/[digitalcollections.union.edu/vendor/laminas/laminas-eventmanager/src/EventManager.php(321)](http://digitalcollections.union.edu/vendor/laminas/laminas-eventmanager/src/EventManager.php(321)): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#31 /home/schaffer/[digitalcollections.union.edu/vendor/laminas/laminas-eventmanager/src/EventManager.php(178)](http://digitalcollections.union.edu/vendor/laminas/laminas-eventmanager/src/EventManager.php(178)): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#32 /home/schaffer/[digitalcollections.union.edu/vendor/laminas/laminas-mvc/src/Application.php(331)](http://digitalcollections.union.edu/vendor/laminas/laminas-mvc/src/Application.php(331)): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#33 /home/schaffer/[digitalcollections.union.edu/index.php(21)](http://digitalcollections.union.edu/index.php(21)): Laminas\Mvc\Application->run()
#34 {main}

**Comment by CSSSchaffer** [comment]
UPDATE: 
Manually re-installing Any Cloud 2.0.0 seemed to have fixed the issue. We don't know exactly how, other than to chalk it up to some corrupted file in the plugin?

**Comment by jaredhowland** [comment]
Since re-installing seems to fix the issue we will close this.
