### ISSUE TITLE
iPhone does not display images from Azure Blob Storage

### ISSUE THREAD

**Issue by bjoeysouza** [HBLL-Collection-Development/omeka-s-any-cloud#38]
**Describe the bug**
There are seemly random images that do not display on an iPhone when viewing the images that were uploaded to Azure blob storage via the Any Cloud module. 

**To Reproduce**
1. Go to https://exhibits.sos.ca.gov/s/exhibits/item-set/7 on an iPhone
2. Scroll down to view the items
3. See that only 3 thumbnails are visible

**Expected behavior**
Following the same steps on a desktop or android and you'll see that all the thumbnails render as expected

**Screenshots**
![IMG_0025](https://github.com/HBLL-Collection-Development/omeka-s-any-cloud/assets/88113958/00843561-7ea7-4f15-b92d-ab2920f937aa)
See a thumbnail that renders and one that doesn't

**Smartphone (please complete the following information):**
- Device: iPhone 11 Pro
- OS: iOS 16.5
- Browser: Safari
- Version 16

**Comment by jaredhowland** [comment]
Can you check the following for me please:

1. Does your Azure blob directory have the correct permissions to publicly show the images?
2. Are the missing images actually in the directory?
3. Do these images show up when using a desktop or other browser?

There’s a chance this is a bug with Omeka-S and the theme you are using so I’m trying to rule that out before digging deeper.

**Comment by bjoeysouza** [comment]
1. Yes the blob directory has Blob access (anonymous read access for blobs only)
2. The images are verified in the directory
3. The images show up fine on Android, Mac, and Windows. I tried using Chrome for iPhone and that didn't work either

I'd like to note that even though the images cannot be viewed on iPhone, holding and selecting "download linked file" allows the user to download the image and then view it in the iPhone file explorer. Additionally I used the iPhone debugging feature by connecting an iPhone to a Macbook and there are no console errors. The network tab shows that the images are being downloaded fine, but still the iPhone will not render certain images.

**Comment by jaredhowland** [comment]
If the images are being uploaded to the blob and being served to the browser then the AnyCloud module is working correctly. This is likely a browser bug or a bug with the way the theme is rendering the content. Or a bug with Omeka-S itself in displaying the images.

I will leave this open for a couple more days but will likely close it unless we can find a reason to believe it is a problem with AnyCloud.
