### ISSUE TITLE
A plugin by the name "AnyCloud\Form\Configform" was not found in the plugin manager

### ISSUE THREAD

**Issue by jonfackrell** [HBLL-Collection-Development/omeka-s-any-cloud#4]
**Describe the bug**
When I try to edit the module's settings in the admin interface I get an error and the following is written to the logs:

Zend\Form\Exception\InvalidElementException: A plugin by the name "AnyCloud\Form\Configform" was not found in the plugin manager Zend\Form\FormElementManager\FormElementManagerV3Polyfill in /home/forge/spc.ask-a-librarian.com/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerTrait.php:41

**To Reproduce**
1. I unzipped the module package and uploaded the files to the modules directory on the server.
2. The Module.php file was missing so I uploaded the current file from the Github repository.
3. After navigating the modules area of the admin site, I installed the module and clicked the button to configure the module settings.
4. I received an error so I went to the logs and found the above error message.

**Expected behavior**
I was hoping to be able to configure the module settings for a cloud storage provider.

**Comment by jaredhowland** [comment]
Thanks for the pull request and fixes. I've merged them and released v1.0.1 and closed this issue. Let me know if this still does not fix your issue. If not, I will need to do a fresh install of Omeka S and do some troubleshooting.
