### ISSUE TITLE
Laminas\ServiceManager\Exception\ServiceNotCreatedException

### ISSUE THREAD

**Issue by LukeNzk** [HBLL-Collection-Development/omeka-s-any-cloud#44]
I installed AnyCloud and I'm trying to use it with AWS S3 bucket. I provided IAM user key/secret
![image](https://github.com/HBLL-Collection-Development/omeka-s-any-cloud/assets/7074274/8db1d5dc-148a-4ebb-92d1-eaf82e140a1c)

The AWS policy is as follows:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
        }
    ]
}
```

I'm getting an exception when I click `Create Item`
```
Laminas\ServiceManager\Exception\ServiceNotCreatedException
Service with name "AnyCloud\File\Store\Aws" could not be created. Reason: Credentials must be an instance of 'Aws\Credentials\CredentialsInterface, an associative array that contains "key", "secret", and an optional "token" key-value pairs, a credentials provider function, or false.

Details:

InvalidArgumentException: Credentials must be an instance of 'Aws\Credentials\CredentialsInterface, an associative array that contains "key", "secret", and an optional "token" key-value pairs, a credentials provider function, or false. in /var/www/html/modules/AnyCloud/vendor/aws/aws-sdk-php/src/ClientResolver.php:604
Stack trace:
#0 /var/www/html/modules/AnyCloud/vendor/aws/aws-sdk-php/src/ClientResolver.php(379): Aws\ClientResolver::_apply_credentials()
#1 /var/www/html/modules/AnyCloud/vendor/aws/aws-sdk-php/src/AwsClient.php(222): Aws\ClientResolver->resolve()
#2 /var/www/html/modules/AnyCloud/vendor/aws/aws-sdk-php/src/S3/S3Client.php(358): Aws\AwsClient->__construct()
#3 /var/www/html/modules/AnyCloud/src/Service/File/Store/AbstractAwsS3V3Factory.php(22): Aws\S3\S3Client->__construct()
#4 /var/www/html/modules/AnyCloud/src/Service/File/Store/AbstractFlysystemFactory.php(49): AnyCloud\Service\File\Store\AbstractAwsS3V3Factory->getFilesystemAdapter()
#5 /var/www/html/modules/AnyCloud/src/Service/File/Store/AbstractFlysystemFactory.php(21): AnyCloud\Service\File\Store\AbstractFlysystemFactory->getStore()
#6 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): AnyCloud\Service\File\Store\AbstractFlysystemFactory->__invoke()
#7 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#8 /var/www/html/modules/AnyCloud/src/Service/File/Store/AnyCloudFactory.php(35): Laminas\ServiceManager\ServiceManager->get()
#9 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): AnyCloud\Service\File\Store\AnyCloudFactory->__invoke()
#10 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#11 /var/www/html/application/src/File/TempFileFactory.php(45): Laminas\ServiceManager\ServiceManager->get()
#12 /var/www/html/application/src/Service/File/TempFileFactoryFactory.php(12): Omeka\File\TempFileFactory->__construct()
#13 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): Omeka\Service\File\TempFileFactoryFactory->__invoke()
#14 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#15 /var/www/html/application/src/Service/File/UploaderFactory.php(12): Laminas\ServiceManager\ServiceManager->get()
#16 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): Omeka\Service\File\UploaderFactory->__invoke()
#17 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#18 /var/www/html/application/src/Service/Media/Ingester/UploadFactory.php(17): Laminas\ServiceManager\ServiceManager->get()
#19 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): Omeka\Service\Media\Ingester\UploadFactory->__invoke()
#20 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(206): Laminas\ServiceManager\ServiceManager->doCreate()
#21 /var/www/html/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(171): Laminas\ServiceManager\ServiceManager->get()
#22 /var/www/html/application/src/Media/Ingester/Manager.php(17): Laminas\ServiceManager\AbstractPluginManager->get()
#23 /var/www/html/application/src/Controller/Admin/ItemController.php(386): Omeka\Media\Ingester\Manager->get()
#24 /var/www/html/application/src/Controller/Admin/ItemController.php(235): Omeka\Controller\Admin\ItemController->getMediaForms()
#25 /var/www/html/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\ItemController->addAction()
#26 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#27 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#28 /var/www/html/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil()
#29 /var/www/html/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch()
#30 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch()
#31 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#32 /var/www/html/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil()
#33 /var/www/html/index.php(21): Laminas\Mvc\Application->run()
#34 {main}

Next Laminas\ServiceManager\Exception\ServiceNotCreatedException: Service with name "AnyCloud\File\Store\Aws" could not be created. Reason: Credentials must be an instance of 'Aws\Credentials\CredentialsInterface, an associative array that contains "key", "secret", and an optional "token" key-value pairs, a credentials provider function, or false. in /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php:622
Stack trace:
#0 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#1 /var/www/html/modules/AnyCloud/src/Service/File/Store/AnyCloudFactory.php(35): Laminas\ServiceManager\ServiceManager->get()
#2 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): AnyCloud\Service\File\Store\AnyCloudFactory->__invoke()
#3 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#4 /var/www/html/application/src/File/TempFileFactory.php(45): Laminas\ServiceManager\ServiceManager->get()
#5 /var/www/html/application/src/Service/File/TempFileFactoryFactory.php(12): Omeka\File\TempFileFactory->__construct()
#6 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): Omeka\Service\File\TempFileFactoryFactory->__invoke()
#7 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#8 /var/www/html/application/src/Service/File/UploaderFactory.php(12): Laminas\ServiceManager\ServiceManager->get()
#9 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): Omeka\Service\File\UploaderFactory->__invoke()
#10 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#11 /var/www/html/application/src/Service/Media/Ingester/UploadFactory.php(17): Laminas\ServiceManager\ServiceManager->get()
#12 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): Omeka\Service\Media\Ingester\UploadFactory->__invoke()
#13 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(206): Laminas\ServiceManager\ServiceManager->doCreate()
#14 /var/www/html/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(171): Laminas\ServiceManager\ServiceManager->get()
#15 /var/www/html/application/src/Media/Ingester/Manager.php(17): Laminas\ServiceManager\AbstractPluginManager->get()
#16 /var/www/html/application/src/Controller/Admin/ItemController.php(386): Omeka\Media\Ingester\Manager->get()
#17 /var/www/html/application/src/Controller/Admin/ItemController.php(235): Omeka\Controller\Admin\ItemController->getMediaForms()
#18 /var/www/html/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\ItemController->addAction()
#19 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#20 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#21 /var/www/html/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil()
#22 /var/www/html/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch()
#23 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch()
#24 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#25 /var/www/html/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil()
#26 /var/www/html/index.php(21): Laminas\Mvc\Application->run()
#27 {main}
```

**Comment by LukeNzk** [comment]
It worked when I used server-side configuration (editing conf file).

**Comment by LATAEVIA** [comment]
I second this motion, except server-side configuration also logged 500 error for me.

**Comment by jajm** [comment]
Which version of AnyCloud are you using ?
Can you show the result of the following SQL query: `select value from setting where id = 'anycloud_aws'` ? (don't forget to hide secrets)

@LATAEVIA can you share the relevant section of your configuration file ?

**Comment by LukeNzk** [comment]
I picked latest release 3.1.5. I'll have to revert my current settings from local to repro it again, but I can do it if it's helpful for you. Btw. there's also one annoyance ;D I thought that when I add the config to server file instead of in visual client it'll be hidden from public but it is still visible in the config panel so all the other admins will be able to see it and potentially access the archive's s3 bucket without any restrictions...

**Comment by jajm** [comment]
> I thought that when I add the config to server file instead of in visual client it'll be hidden from public but it is still visible in the config panel so all the other admins will be able to see it and potentially access the archive's s3 bucket without any restrictions...

I'm not sure to understand. If you only configure it in `config/local.config.php` it shouldn't be visible in the module configuration page. Hiding it from the other admins is the whole point of being able to configure it in `config/local.config.php` :)
You should be able to clear the module configuration form entirely

**Comment by LukeNzk** [comment]
I suppose it's a bug. I cannot clear it because the form is greyed out. I assume that first I'd need to remove the configuration from local.config.php, clear the visual config from the form and bring back local.config.php... Just look at the screen :)

![image](https://github.com/HBLL-Collection-Development/omeka-s-any-cloud/assets/7074274/fc39ac20-8dfb-4ffd-8e27-f8a4a2632f41)

**Comment by LukeNzk** [comment]
Or I can just remove it with SQL query.

**Comment by jajm** [comment]
Oh okay. As a quick fix (if you prefer not to use SQL query) you can comment out the 'file_store/aws' section in local.config.php, clear the form, then uncomment local.config.php. I'll see what I can do to be more user-friendly.

**Comment by LATAEVIA** [comment]
When configured from admin side and I attempt to add an asset:

<img width="949" alt="Screenshot 2023-11-06 at 8 08 46 AM" src="https://github.com/HBLL-Collection-Development/omeka-s-any-cloud/assets/12283026/f7448425-65e9-412e-90d9-93fcb3dac5cb">

With likely unrelated error logging at the top of the module config page:
`Warning: Array to string conversion in /var/www/html/forked-omeks-s/vendor/laminas/laminas-form/src/Element.php on line 56`

And this error specifically when I access assets page:

`Omeka S encountered an error
Laminas\ServiceManager\Exception\ServiceNotCreatedException
Service with name "AnyCloud\File\Store\Aws" could not be created. Reason: Credentials must be an instance of 'Aws\Credentials\CredentialsInterface, an associative array that contains "key", "secret", and an optional "token" key-value pairs, a credentials provider function, or false.`

`Details:`

`InvalidArgumentException: Credentials must be an instance of 'Aws\Credentials\CredentialsInterface, an associative array that contains "key", "secret", and an optional "token" key-value pairs, a credentials provider function, or false. in /var/www/html/forked-omeks-s/modules/AnyCloud/vendor/aws/aws-sdk-php/src/ClientResolver.php:604
Stack trace:
#0 /var/www/html/forked-omeks-s/modules/AnyCloud/vendor/aws/aws-sdk-php/src/ClientResolver.php(379): Aws\ClientResolver::_apply_credentials()
#1 /var/www/html/forked-omeks-s/modules/AnyCloud/vendor/aws/aws-sdk-php/src/AwsClient.php(222): Aws\ClientResolver->resolve()
#2 /var/www/html/forked-omeks-s/modules/AnyCloud/vendor/aws/aws-sdk-php/src/S3/S3Client.php(358): Aws\AwsClient->__construct()
#3 /var/www/html/forked-omeks-s/modules/AnyCloud/src/Service/File/Store/AbstractAwsS3V3Factory.php(22): Aws\S3\S3Client->__construct()
#4 /var/www/html/forked-omeks-s/modules/AnyCloud/src/Service/File/Store/AbstractFlysystemFactory.php(49): AnyCloud\Service\File\Store\AbstractAwsS3V3Factory->getFilesystemAdapter()
#5 /var/www/html/forked-omeks-s/modules/AnyCloud/src/Service/File/Store/AbstractFlysystemFactory.php(21): AnyCloud\Service\File\Store\AbstractFlysystemFactory->getStore()
#6 /var/www/html/forked-omeks-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): AnyCloud\Service\File\Store\AbstractFlysystemFactory->__invoke()
#7 /var/www/html/forked-omeks-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#8 /var/www/html/forked-omeks-s/modules/AnyCloud/src/Service/File/Store/AnyCloudFactory.php(35): Laminas\ServiceManager\ServiceManager->get()
#9 /var/www/html/forked-omeks-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): AnyCloud\Service\File\Store\AnyCloudFactory->__invoke()
#10 /var/www/html/forked-omeks-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#11 /var/www/html/forked-omeks-s/application/src/Api/Representation/AbstractResourceRepresentation.php(262): Laminas\ServiceManager\ServiceManager->get()
#12 /var/www/html/forked-omeks-s/application/src/Api/Representation/AssetRepresentation.php(55): Omeka\Api\Representation\AbstractResourceRepresentation->getFileUrl()
#13 /var/www/html/forked-omeks-s/application/src/Api/Representation/AbstractRepresentation.php(122): Omeka\Api\Representation\AssetRepresentation->assetUrl()
#14 /var/www/html/forked-omeks-s/application/src/View/Helper/Thumbnail.php(21): Omeka\Api\Representation\AbstractRepresentation->thumbnailDisplayUrl()
#15 /var/www/html/forked-omeks-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(407): Omeka\View\Helper\Thumbnail->__invoke()
#16 /var/www/html/forked-omeks-s/application/view/omeka/admin/asset/browse.phtml(50): Laminas\View\Renderer\PhpRenderer->__call()
#17 /var/www/html/forked-omeks-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519): include('...')
#18 /var/www/html/forked-omeks-s/vendor/laminas/laminas-view/src/View.php(194): Laminas\View\Renderer\PhpRenderer->render()
#19 /var/www/html/forked-omeks-s/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View->render()
#20 /var/www/html/forked-omeks-s/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View->renderChildren()
#21 /var/www/html/forked-omeks-s/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(98): Laminas\View\View->render()
#22 /var/www/html/forked-omeks-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render()
#23 /var/www/html/forked-omeks-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners()
#24 /var/www/html/forked-omeks-s/vendor/laminas/laminas-mvc/src/Application.php(360): Laminas\EventManager\EventManager->triggerEvent()
#25 /var/www/html/forked-omeks-s/vendor/laminas/laminas-mvc/src/Application.php(341): Laminas\Mvc\Application->completeRequest()
#26 /var/www/html/forked-omeks-s/index.php(21): Laminas\Mvc\Application->run()
#27 {main}`

`Next Laminas\ServiceManager\Exception\ServiceNotCreatedException: Service with name "AnyCloud\File\Store\Aws" could not be created. Reason: Credentials must be an instance of 'Aws\Credentials\CredentialsInterface, an associative array that contains "key", "secret", and an optional "token" key-value pairs, a credentials provider function, or false. in /var/www/html/forked-omeks-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php:622
Stack trace:
#0 /var/www/html/forked-omeks-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#1 /var/www/html/forked-omeks-s/modules/AnyCloud/src/Service/File/Store/AnyCloudFactory.php(35): Laminas\ServiceManager\ServiceManager->get()
#2 /var/www/html/forked-omeks-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): AnyCloud\Service\File\Store\AnyCloudFactory->__invoke()
#3 /var/www/html/forked-omeks-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#4 /var/www/html/forked-omeks-s/application/src/Api/Representation/AbstractResourceRepresentation.php(262): Laminas\ServiceManager\ServiceManager->get()
#5 /var/www/html/forked-omeks-s/application/src/Api/Representation/AssetRepresentation.php(55): Omeka\Api\Representation\AbstractResourceRepresentation->getFileUrl()
#6 /var/www/html/forked-omeks-s/application/src/Api/Representation/AbstractRepresentation.php(122): Omeka\Api\Representation\AssetRepresentation->assetUrl()
#7 /var/www/html/forked-omeks-s/application/src/View/Helper/Thumbnail.php(21): Omeka\Api\Representation\AbstractRepresentation->thumbnailDisplayUrl()
#8 /var/www/html/forked-omeks-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(407): Omeka\View\Helper\Thumbnail->__invoke()
#9 /var/www/html/forked-omeks-s/application/view/omeka/admin/asset/browse.phtml(50): Laminas\View\Renderer\PhpRenderer->__call()
#10 /var/www/html/forked-omeks-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519): include('...')
#11 /var/www/html/forked-omeks-s/vendor/laminas/laminas-view/src/View.php(194): Laminas\View\Renderer\PhpRenderer->render()
#12 /var/www/html/forked-omeks-s/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View->render()
#13 /var/www/html/forked-omeks-s/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View->renderChildren()
#14 /var/www/html/forked-omeks-s/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(98): Laminas\View\View->render()
#15 /var/www/html/forked-omeks-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render()
#16 /var/www/html/forked-omeks-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners()
#17 /var/www/html/forked-omeks-s/vendor/laminas/laminas-mvc/src/Application.php(360): Laminas\EventManager\EventManager->triggerEvent()
#18 /var/www/html/forked-omeks-s/vendor/laminas/laminas-mvc/src/Application.php(341): Laminas\Mvc\Application->completeRequest()
#19 /var/www/html/forked-omeks-s/index.php(21): Laminas\Mvc\Application->run()
#20 {main}`

**Comment by LATAEVIA** [comment]
When configured serve- side and I attempt to add an asset:

<img width="1162" alt="Screenshot 2023-11-06 at 8 21 09 AM" src="https://github.com/HBLL-Collection-Development/omeka-s-any-cloud/assets/12283026/965616a3-a361-4c1f-a376-9fc94239317a">

-

<img width="1168" alt="Screenshot 2023-11-06 at 8 24 25 AM" src="https://github.com/HBLL-Collection-Development/omeka-s-any-cloud/assets/12283026/1335b121-f5ed-4a42-9507-81c2494ad931">

-

Anything previously uploaded is returning a 400 and new uploads are returning 500.

In case it helps, V3.0.1 is working with the Admin config.

**Comment by jajm** [comment]
I just pushed 2 commits that should fix the warning ("Warning: Array to string conversion") and the ServiceNotCreatedException

The other error is something else.. Can you open another issue for this ?
