### ISSUE TITLE
Enabling AnyCloud causes /admin/item to throw 500 Error

### ISSUE THREAD

**Issue by jlinsos** [HBLL-Collection-Development/omeka-s-any-cloud#49]
**Describe the bug**
Enabling AnyCloud causes /admin/item to throw 500 Error

Fatal error: Could not check compatibility between AnyCloud\Service\File\Store\AzureFactory::getFilesystemAdapter(array $config): AnyCloud\Service\File\Store\FilesystemAdapter and AnyCloud\Service\File\Store\AbstractFlysystemFactory::getFilesystemAdapter(array $config): League\Flysystem\FilesystemAdapter, because class AnyCloud\Service\File\Store\FilesystemAdapter is not available in

**To Reproduce**
1. Enable AnyCloud on latest Omeka S version
2. Items on left hand menu
4. HTML page partially renders with 500 error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: Linux
- Browser any
- Version latest version of Omeka S, AnyCloud, PHP 8.3

**Comment by jajm** [comment]
Thanks for reporting the issue. It is now fixed in [v3.2.1](https://github.com/HBLL-Collection-Development/omeka-s-any-cloud/releases/tag/v3.2.1)
